# Generated by Django 3.2 on 2021-07-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsevent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tsevent',
            name='ide',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Nomber Event'),
        ),
        migrations.AlterField(
            model_name='tsevent',
            name='note',
            field=models.CharField(max_length=255, verbose_name='note for Event'),
        ),
    ]
